<?php 
/* This is an autogenerated file by Bootstrap.php */
return array (
  'core' => 
  array (
    0 => 'TaskCore.php',
    1 => 'WebCore.php',
    2 => 'WsCore.php',
  ),
  'models' => 
  array (
    0 => 'BaseDictionaryModel.php',
    1 => 'BaseModel.php',
    2 => 'BaseUsersModel.php',
    3 => 'BaseUsersTokensModel.php',
  ),
  'phalcon' => 
  array (
    0 => 'AppClassMap.php',
    1 => 'AppPlugins.php',
    2 => 'AppServices.php',
  ),
  'qr' => 
  array (
    0 => 'QRMaker.php',
  ),
  'traits' => 
  array (
    0 => 'AccountAuth.php',
    1 => 'AccountPass.php',
    2 => 'Errors.php',
    3 => 'Facebook.php',
    4 => 'Guzzle.php',
    5 => 'Ses.php',
    6 => 'Session.php',
    7 => 'TicketStorage.php',
  ),
  'transbank' => 
  array (
    0 => 'CCOneClick.php',
    1 => 'CCSoapClient.php',
    2 => 'CCWebpay.php',
    3 => 'CCWebpayClient.php',
  ),
  'utils' => 
  array (
    0 => 'Cryptify.php',
    1 => 'DateHelper.php',
    2 => 'FormHelper.php',
    3 => 'GPS.php',
    4 => 'GetText.php',
    5 => 'PdfHelper.php',
    6 => 'ReCaptcha.php',
    7 => 'Slug.php',
    8 => 'StorageS3.php',
    9 => 'UserAgent.php',
  ),
);
?>