<?php
/**
 * This file generates a class map file to be loaded in phalcon (AppLoader.php)
 * @author Nicolas Pulido <nicolas.pulido@crazycake.cl>
 */

//get modules
$modules   = scandir(__DIR__);
$class_map = [];

//grab printed data
ob_start();

//loop through modules
foreach ($modules as $dir) {

	$dir_path = __DIR__."/".$dir;
	//check for a directory
	if (!is_dir($dir_path) || strpos($dir, '.') !== false)
		continue;

	$files 	 = scandir(__DIR__."/".$dir);
	$classes = [];
	//loop though files
	foreach ($files as $file) {

		$file_path = $dir_path."/".$file;

		//check for a file
		if (!is_file($file_path) || strpos($file, '.php') === false)
			continue;

		//push class to array
		array_push($classes, $file);
	}

	if (!empty($classes))
		$class_map[$dir] = $classes;
}

//export data as php syntax
$data = var_export($class_map);
print_r($data);
$php_content = ob_get_contents();
ob_end_clean();

$output = "<?php \n/* This is an autogenerated file by Bootstrap.php */\n";
$output .= "return ".$php_content.";\n?>";

//creates file
file_put_contents(__DIR__."/phalcon/AppClassMap.php", $output);

?>
