#! /bin/bash
# cc-phalcon CLI tools
# author: Nicolas Pulido <nicolas.pulido@crazycake.cl>

# stop execution for exceptions
set -e

#Current path
PROJECT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Package properties
APP_NAME="cc-phalcon"
APP_NAMESPACE="$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]')"

# URLs
BOX_PHAR_URL="https://github.com/box-project/box2/releases/download/2.7.5/box-2.7.5.phar"
PHPDOC_PHAR_URL="http://phpdoc.org/phpDocumentor.phar"
# Local documentation path.
PHPDOC_INPUT_PATH="./"
PHPDOC_OUTPUT_PATH=$PROJECT_PATH"/.docs/"

#script help function
scriptHelp() {
	echo -e "\033[93m"$APP_NAME" core Script\nValid actions:\033[0m"
	echo -e "\033[96m build: Builds phar file with default box.json file.\033[0m"
	echo -e "\033[96m tree: Returns the file tree of phar file.\033[0m"
	echo -e "\033[96m docs: Generates PHP Docs (PHPDoc library is required [phpdoc]).\033[0m"
	exit
}

#commands
case "$1" in

	build)

		# download phar once
		if [ ! -f $PROJECT_PATH"/box.phar" ]; then

			echo -e "\033[94mDownloading box.phar ... \033[0m"
			wget -O box.phar $BOX_PHAR_URL
		fi

		VER=$(git rev-parse --short HEAD)

		# append version to autoload file
		sed -i "6s/.*/DEFINE('CORE_VERSION', '$VER');/" autoload.php

		cd $PROJECT_PATH
		# build, use -v for verbose
		php box.phar build
		# task done!
		echo -e "\033[92mBuilded $VER \033[0m"
	;;

	tree)

		cd $PROJECT_PATH
		php box.phar info -l $APP_NAMESPACE".phar"
		# task done!
		echo -e "\033[92mDone! \033[0m"
	;;

	docs)

		# download phar once
		if [ ! -f $PROJECT_PATH"/phpdoc.phar" ]; then

			echo -e "\033[94mDownloading phpdoc.phar ... \033[0m"
			wget -O phpdoc.phar $PHPDOC_PHAR_URL
		fi

		#PHP
		echo -e "\033[35mGenerating PHP Docs...\033[0m"
		php phpdoc.phar -d $PHPDOC_INPUT_PATH -t $PHPDOC_OUTPUT_PATH --template="responsive-twig"
	;;

	#default
	*)
		scriptHelp
	;;
esac
