#! /bin/bash
# Phalcon App CLI
# author: Nicolas Pulido <nicolas.pulido@crazycake.tech>

# set project path
PROJECT_PATH="$(pwd)"

# app namespace
APP_NAME=${PWD##*/}
CONTAINER_NAME="$(docker ps | grep -o '\w*_'$APP_NAME)"

# app paths
TOOLS_PATH=$PROJECT_PATH"/.tools/"

# stop script if an error occurs
set -e

# help output
help() {

	echo -e "\033[93m > "$APP_NAME" webapp CLI \033[0m"
	echo -e "\033[95m watch: Run JS bundler watcher daemon. Option --m for mailing (mjml).\033[0m"
	echo -e "\033[95m build: Build JS bundle and compile 'po' translation files. \033[0m"
	echo -e "\033[95m trans: Update translations 'po' file. \033[0m"
	echo -e "\033[95m php: Run app php CLI. \033[0m"
	echo -e "\033[95m clean: Clean cache & logs.\033[0m"
	echo -e "\033[97m > admin commands \033[0m"
	echo -e "\033[95m core: Install/update core package (requires cc-phalcon project symbolic link). \033[0m"
	exit
}

# commands
case "$1" in

watch)

	echo -e "\033[95mRunning bundler watcher...\033[0m"

	if [ "$2" = "--m" ]; then

		echo -e "\033[31mMJML watcher...\033[0m"

		./node_modules/mjml/bin/mjml -w ui/mailing/*.volt.mjml --config.minify -o ui/volt/mailing/

	else

		parcel ui/app.js -d public/assets/ --cache-dir .parcel/ --no-source-maps
	fi
;;

build)

	echo -e "\033[95mBuilding bundle... \033[0m"

	parcel build ui/app.js -d public/assets/ --cache-dir .parcel/ --no-source-maps --detailed-report

	echo -e "\033[95mExecuting container '$CONTAINER_NAME' tasks... \033[0m"

	# rev assets in container
	docker exec -it $CONTAINER_NAME bash -c 'php /var/www/app/cli/cli.php main revAssets'

	# translations (gettext)
	bash $TOOLS_PATH"translations.bash" build
;;

trans)

	# translations (gettext)
	bash $TOOLS_PATH"translations.bash" find
;;

php)

	echo -e "\033[95mRunning app php CLI... \033[0m"

	docker exec -it $CONTAINER_NAME bash -c "php /var/www/app/cli/cli.php main ${@:2}"
;;

clean)

	docker exec -it $CONTAINER_NAME bash -c 'find /var/www/storage/cache /var/www/storage/logs -type f \( ! -iname ".*" \) -print0 | xargs -0 rm -f'

	rm -rf $PROJECT_PATH"/.parcel" || true

	echo -e "\033[92mDone! \033[0m"
;;

core)

	bash $TOOLS_PATH"core.bash" "${@:2}"
;;

# defaults
*)
	help
;;
esac
