#! /bin/bash
# webapp CLI

# stop script if an error occurs
set -e
# set project path
PROJECT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# app namespace
APP_NAME=${PWD##*/}

# app paths
TOOLS_PATH=$PROJECT_PATH"/.tools/"
STORAGE_PATH=$PROJECT_PATH"/storage/"
COMPOSER_PATH=$PROJECT_PATH"/vendor/"

# help output
scriptHelp() {
	echo -e "\033[93m"$APP_NAME" webapp CLI\033[0m"
	echo -e "\033[94mDev commands:\033[0m"
	echo -e "\033[95m watch <option>: Runs watcher daemon. Option -m for mailing watcher daemon \033[0m"
	echo -e "\033[95m db: Executes DB migrations (phinx engine).\033[0m"
	echo -e "\033[95m clean: Cleans cache & logs (storage folder).\033[0m"
	echo -e "\033[95m core: installs/updates core package (requires cc-phalcon project symlink). \033[0m"
	echo -e "\033[95m build: build JS & CSS bundles and compile translations. \033[0m"
	echo -e "\033[95m trans: Update translations po file. \033[0m"
	echo -e "\033[95m php-cli: Executes app PHP CLI.\033[0m"
	echo -e "\033[95m aws-cli <option>: Install AWS CLI (pip is required). Use -s for self-update, -c for configuration.\033[0m"
	echo -e "\033[95m aws-cdn: Syncs S3 CDN bucket with app assets.\033[0m"
	exit
}

# commands
case "$1" in

db)

	if [ ! -f $COMPOSER_PATH"bin/phinx" ]; then

		echo -e "\033[31mphinx library not found in composer project folder.\033[0m" && exit
	fi

	echo -e "\033[95mRunning phinx command... \033[0m"

	php $COMPOSER_PATH"bin/phinx" "${@:2}"
	;;

clean)

	# clean storage
	if [ -d $STORAGE_PATH ]; then

		find $STORAGE_PATH"cache" $STORAGE_PATH"logs" -type f \( ! -iname ".*" \) -print0 | xargs -0 sudo rm
	fi

	# task done!
	echo -e "\033[92mDone! \033[0m"
	;;

build)

	# msg
	echo -e "\033[95mGulp build tasks... \033[0m"

	# gulp build task
	gulp build

	# translations
	bash $TOOLS_PATH"translations.bash" build
	;;

watch)

	echo -e "\033[95mRunning gulp watch...\033[0m"

	[[ "$2" = "-m" ]] && gulp watch-m || gulp watch
	;;

watch-m)

	echo -e "\033[95mRunning gulp watch-mailing...\033[0m"

	gulp watch-mailing
	;;

core)

	bash $TOOLS_PATH"core.bash"
	;;

trans)

	bash $TOOLS_PATH"translations.bash" find
	bash $TOOLS_PATH"translations.bash" find
	;;

cli)

	echo -e "\033[95mRunning PHP App CLI... \033[0m"

	php $PROJECT_PATH"/cli/cli.php" "main" "${@:2}"
	;;

aws-cli)

	echo -e "\033[95mChecking python & pip versions... \033[0m"

	python --version
	pip --version

	# instalation
	if [ "$2" = "-c" ]; then

		echo -e "\033[95mDefault region: us-east-1, Default Format Output: json [suggestion]\033[0m"

		aws configure

	elif [ "$2" = "-s" ]; then

		echo -e "\033[95mUpdating AWS CLI... \033[0m"
		sudo pip install --upgrade awscli
	else

		echo -e "\033[95mInstalling AWS CLI... \033[0m"
		sudo pip install awscli
	fi

	#check aws version
	echo -e "\033[95mChecking AWS CLI version... \033[0m"
	#get AWS CLI version
	aws --version
	;;

aws-cdn)

	#sync assets
	SYNC_LOCAL_PATH="$PROJECT_PATH/public/assets/"
	SYNC_REMOTE_PATH="s3://$APP_NAME-cdn/assets/"

	echo -e "\033[95mBucket Syncing $SYNC_LOCAL_PATH -> $SYNC_REMOTE_PATH \033[0m"
	#sync
	aws s3 sync $SYNC_LOCAL_PATH $SYNC_REMOTE_PATH --delete --cache-control max-age=864000 --exclude '*' --include '*.rev.css' --include '*.rev.js'

	#sync images
	SYNC_LOCAL_PATH="$PROJECT_PATH/public/images/"
	SYNC_REMOTE_PATH="s3://$APP_NAME-cdn/images/"

	echo -e "\033[95mBucket Syncing $SYNC_LOCAL_PATH -> $SYNC_REMOTE_PATH \033[0m"
	#sync
	aws s3 sync $SYNC_LOCAL_PATH $SYNC_REMOTE_PATH --delete --cache-control max-age=864000 --exclude '*.htaccess' --exclude '*.DS_Store' --exclude '*.html'

	#sync fonts
	SYNC_LOCAL_PATH="$PROJECT_PATH/public/fonts/"
	SYNC_REMOTE_PATH="s3://$APP_NAME-cdn/fonts/"

	echo -e "\033[95mBucket Syncing $SYNC_LOCAL_PATH -> $SYNC_REMOTE_PATH \033[0m"
	#sync
	aws s3 sync $SYNC_LOCAL_PATH $SYNC_REMOTE_PATH --delete --cache-control max-age=864000 --exclude '*.htaccess' --exclude '*.DS_Store' --exclude '*.html'
	;;

#default
*)
	scriptHelp
    ;;
esac
